### ISSUE TITLE
pub仓库的Example有误

### ISSUE THREAD

**Issue by MrRuanCoder** [luo6luo/ifly_speech_recognition#3]
pub仓库的example里控制台能成功打印返回的json结果，但文字无法正常显示在界面上，应该是这部分有bug(_result 始终为空):
```
    // 语音识别回调
    _recognitionService.onRecordResult().listen((message) {
      EasyLoading.dismiss();
      setState(() {
        _result = message;
      });
    }, onError: (err) {
      EasyLoading.dismiss();
      debugPrint(err);
    });
```

**Comment by luo6luo** [comment]
谢谢你提出的宝贵问题，关于该问题：
1、`example` 中，关于权限设置有误，会导致返回数据为空，现已在 [0.3.2](https://github.com/luo6luo/ifly_speech_recognition/releases/tag/0.3.2) 版本中修复，iOS、Android、线上项目都已真机调试无误。
2、出现该问题，也可能是 `_recognitionService.onRecordResult().listen((message)) {}` 监听过迟，可在 `initState` 方法中实现。

具体的问题，如果可以，希望能够贴上控制台输出相关内容，感恩ღ( ´･ᴗ･` )比心。

**Comment by luo6luo** [comment]
> pub仓库的example里控制台能成功打印返回的json结果，但文字无法正常显示在界面上，应该是这部分有bug(_result 始终为空):
> 
> ```
>     // 语音识别回调
>     _recognitionService.onRecordResult().listen((message) {
>       EasyLoading.dismiss();
>       setState(() {
>         _result = message;
>       });
>     }, onError: (err) {
>       EasyLoading.dismiss();
>       debugPrint(err);
>     });
> ```

谢谢你提出的宝贵问题，关于该问题：
1、`example` 中关于权限设置有误，会导致返回结果错误，现已在 [0.3.2](https://github.com/luo6luo/ifly_speech_recognition/releases/tag/0.3.2) 版本中修复，可以运行查看。
2、如果监听为空，也可能是数据解析或者监听过晚造成，这个需要控制台数据调试。

如果还有相关错误，如果可以的话，请贴上相关的控制台输出信息，感恩ღ( ´･ᴗ･` )比心。
