### ISSUE TITLE
_recognitionService.onRecordResult().listen((message) is empty

### ISSUE THREAD

**Issue by marsloving** [luo6luo/ifly_speech_recognition#5]
`  void _initRecorder() async {
    _havePermission = await _checkPermission();

    if (!_havePermission) {
      // 授权失败
      EasyLoading.showToast('请开启麦克风权限');
      return;
    }

    // 初始化语音识别服务
    await _recognitionService.initRecorder();

    // EasyLoading.dismiss();

    // 语音识别回调
    _recognitionService.onRecordResult().listen((message) {
      
      print("message$message");

      EasyLoading.dismiss();
      setState(() {
        _result = message;

      });
    }, onError: (err) {
      EasyLoading.dismiss();
      debugPrint(err);
    });`
    
    
    
   the issue is    the message  in  _recognitionService.onRecordResult().listen((message)  is empty
   because the resultlist was not assigned correctly.
   
   `  /// 解析数据
  void _analysisData(SpeechRecognitionResultDataResult? result) {
    debugPrint('result1: ${result}');
    if (result == null) return;

    // 确保serialNumber是非空的，这里减1是因为假设serialNumber从1开始计数，而列表索引从0开始
    final index = (result.serialNumber ?? 1) - 1;

    if ((result.serialNumber ?? 0) > _resultList.length) {
      // 扩容
      final addLength = result.serialNumber! - _resultList.length;
      _resultList.addAll(List.filled(addLength, null));

      // 更新或添加result到指定位置
      _resultList[index] = result;
    }`

我增加了
 final index = (result.serialNumber ?? 1) - 1;
_resultList[index] = result;

用作解决_resultList 为 空值 的问题。从而使得 _recognitionService.onRecordResult().listen((message) 获得正确的值

**Comment by luo6luo** [comment]
@marsloving 非常感谢你的指正，针对 #5 的问题，已经修复优化，在新版本 [1.0.2](https://github.com/luo6luo/ifly_speech_recognition/releases/tag/1.0.2) 中已修复。
