### ISSUE TITLE
无法实时识别

### ISSUE THREAD

**Issue by coderyang123321** [luo6luo/ifly_speech_recognition#6]
大佬，想问一下，这个目前还不能实时识别吗，就是一边录音，一边识别出来文字，我现在用这个，必须点了停止录音后，再去调用speechRecognition()这个方法，才能返回识别后的数据,还是说我调用speechRecognition的顺序有问题

**Comment by luo6luo** [comment]
> 大佬，想问一下，这个目前还不能实时识别吗，就是一边录音，一边识别出来文字，我现在用这个，必须点了停止录音后，再去调用speechRecognition()这个方法，才能返回识别后的数据,还是说我调用speechRecognition的顺序有问题

这个包调用的是[科大讯飞 语音听写 API](https://www.xfyun.cn/doc/asr/voicedictation/API.html)，它是根据你上传的语音进行文字转换。
根据你的需求来看，你可以看看 [实时语音转写 API](https://www.xfyun.cn/doc/asr/rtasr/API.html#%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E) 这个API是否能满足。

希望这个回答能够帮助你😁
