### ISSUE TITLE
1.0.4 android  运行报错

### ISSUE THREAD

**Issue by JakeGi** [luo6luo/ifly_speech_recognition#7]
./../../../../../.pub-cache/hosted/pub.dev/ifly_speech_recognition-1.0.4/lib/src/speech_recognition_service.dart:436:48: Error: The argument type 'StreamSink<Food>' can't be assigned to the parameter type 'StreamSink<Uint8List>?'.
 - 'StreamSink' is from 'dart:async'.
 - 'Food' is from 'package:flutter_sound/public/tau.dart' ('../../../../../../.pub-cache/hosted/pub.dev/flutter_sound-9.16.3/lib/public/tau.dart').
 - 'Uint8List' is from 'dart:typed_data'.
          toStream: _mRecordingDataController!.sink,
                                               ^
Target kernel_snapshot_program failed: Exception
2

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/apple/development/flutter/bin/flutter'' finished with non-zero exit value 1

**Comment by luo6luo** [comment]
> ./../../../../../.pub-cache/hosted/pub.dev/ifly_speech_recognition-1.0.4/lib/src/speech_recognition_service.dart:436:48: Error: The argument type 'StreamSink' can't be assigned to the parameter type 'StreamSink?'.
> 
> * 'StreamSink' is from 'dart:async'.
> * 'Food' is from 'package:flutter_sound/public/tau.dart' ('../../../../../../.pub-cache/hosted/pub.dev/flutter_sound-9.16.3/lib/public/tau.dart').
> * 'Uint8List' is from 'dart:typed_data'.
>   toStream: _mRecordingDataController!.sink,
>   ^
>   Target kernel_snapshot_program failed: Exception
>   2
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command '/Users/apple/development/flutter/bin/flutter'' finished with non-zero exit value 1

非常感谢您的提问，问题已在[1.0.5](https://github.com/luo6luo/ifly_speech_recognition/releases/tag/1.0.5)中修复。
